# Color Scheme
color: 
  PureBlue: false
  GrayBlue: true
  DeepBlue: false
  DarkBlue: false
  Gradient: false

# Header
menu:
  Home: /
  Categories: /categories
  Archives: /archives
  Tags: /tags
  About: /about

# Content
# Site favicon
favicon: /images/avatar.gif
word_count: true

# Footer
# Comment
valine:
  enable: false 
  appid:   # your App ID
  appkey:  # your App Key
  notify: false      # mail notifier 
  verify: false     # Verification code
  placeholder: Just talk here...... # comment box placeholder
  avatar: mm # gravatar style
  pageSize: 10 # pagination size
  visitor: false # Statistics of article visits

# copyright info text
copyright_info: Copyright © 2018 - 2019 My Blog

