Menu:
  Home: Home
  Categories: Categories
  Archives: Archives
  Tags: Tags
  About: About

Paginator:
  Prev: Previous Page
  Next: Next Page

Readmore:
  Text: Read More

Post-info:
  Date: Date
  Tags: Tags 

Catalog-info:
  Text: Article Catalog

toTop-info:
  Text: To the Top  

Tag-info:
  Text:  tags in total

Posts-info:
  Text1: Wow!
  Text2:  posts in total  

Categories-info:
  Text: categories in total 
